electron-userland/electron-wix-msi

.appveyor.yml, .travis.yml, __tests__/creator-spec.ts, package.json, tsconfig.json
In https://github.com/electron-userland/electron-forge/pull/378 we found that this module works with Node 6, so we might as well change the Node requirement accordingly. This also changes the CI config to test against Node 6.x.
=> Indicate Node 6 compatibility & test against it

__tests__/creator-spec.ts, src/creator.ts
Fixes the following `tsc` error:
```
src/creator.ts(262,39): error TS2345: Argument of type 'string | undefined' is not assignable to para
meter of type 'string'.
Type 'undefined' is not assignable to type 'string'.
262       : ['/a', '/f', `"${path.resolve(certificateFile)}"`, '/p', `"${certificatePassword}"`];
```
This started happening when https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22567 was released.
=> Raise error when signing sans certificateFile

README.md, __tests__/creator-spec.ts, src/creator.ts
This adds an `extensions` configuration property that allows specifying which extensions to use.
=> Allow (custom) extensions to be used

__tests__/creator-spec.ts, src/creator.ts
* Fixes conditions with certificateFile and signWtihParams
* Removes bad quotes around arguments (node does these fore you)
=> fix: make code signing work

__tests__/creator-spec.ts, src/creator.ts, static/component.xml, static/wix.xml
The desired architecture can now be set through and additional option property that defaults back to x86. This allows backwards compatibility. If the architecture is set to x64 then all package and components will set to 64 bit.
e.g.
```
async function harness() {
const msiCreator = new MSICreator({
appDirectory: APP_DIR,
exe: 'slack',
manufacturer: 'Slack Technologies',
name: 'Slack',
outputDirectory: OUT_DIR,
description: 'Test',
ui: {
chooseDirectory: true
},
version: '1.2.3.4',
arch: 'x64'
});
```
=> Adds 64 bit support

README.md, __tests__/creator-spec.ts, src/creator.ts, static/wix.xml
This allows to override the shortcut name that shows up in the startmenu.
=> Allow shortcut naming

src/creator.ts
This patch is related to https://github.com/felixrieseberg/electron-wix-msi/issues/35
=> fix: taking into account template from ui property

README.md, __tests__/creator-spec.ts, src/creator.ts
Specify a specific culture for `light.exe` to build, instead of the default cultures. [specifying_cultures_to_build](https://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/specifying_cultures_to_build.html)
=> Allow specifying a specific culture for light.exe to build using the culture switch

static/wix.xml
In upgrade scenarios the installation of an App can become corrupted if the App is running, files are locked and these files carry the same version number in the previous App version. Also the machine can reboot unexpectedly unless explicitly avoided bu providing command line parameters. By overwriting the defaults of two properties these issues can be avoided.
[REINSTALLMODE ](https://docs.microsoft.com/en-us/windows/win32/msi/reinstallmode) is set to emus instead of the default omus. This way its guaranteed that files of same version are overwritten to. 
Why is that necessary you ask? Well since we introduced upgrade code to allow uninstallation of previous version of the package it means that an uninstall task is run. That uninstall will be confronted with files and use. It then …
=> fix: avoids surprising reboot, avoids install corruption in edge case

__tests__/creator-spec.ts, e2e/src/e2e-auto-updater.ts, e2e/src/utils/installer.ts, e2e/src/utils/ntfs.ts, package-lock.json, static/updater-permissions.xml, static/wix.xml
When installing the auto-updater let IT choose the user group that gets access rights to the install folder. The user group can be configured via command line to the MSI. e.g. `UPDATERUSERGROUP=DomainUsers`
=> Configurable user group ntfs

__tests__/creator-spec.ts, __tests__/utils/array-to-tree-spec.ts, e2e/src/e2e-auto-launch.ts, e2e/src/e2e-auto-updater.ts, e2e/src/e2e-msi.ts, e2e/src/e2e-per-user.ts, e2e/src/utils/installer.ts, src/creator.ts, src/utils/array-to-tree.ts, static/wix.xml
With his PR the MSI can be installed as a user. No UAC prompt and all data go into the user profile. The default installMode can also be chosen. For backward compatibility the default stays perMachine.
=> Allow per user install

src/creator.ts, src/interfaces.ts, static/registry-component.xml
When removing the Auto-Updater feature the custom reg Uninstall key would disappear. This fixes it.
=> fix: do not delete uninstall reg when removing auto-updater

__tests__/creator-spec.ts, e2e/src/e2e-auto-updater.ts, e2e/src/utils/installer.ts, e2e/src/utils/registry.ts, src/creator.ts, static/wix.xml
After some reconsideration, the auto-updater will no be install as it would require to soften the NTFS access rights. That might not be desired if customers never plan to use the auto-updater. 
With this change, the auto-updater and permissions will only be installed when the feature is installed. However, customers can also choose to install the auto-updater but keep it disabled initially by overwriting the MSI parameter  AUTOUPDATEENABLED with a 0.  The corresponding registry key can be later controlled via GPO
=> No auto updater by default

__tests__/creator-spec.ts, e2e/src/e2e-auto-launch.ts, e2e/src/e2e-per-user.ts, e2e/src/utils/app-process.ts, harness/harness.js, src/creator.ts
We should be able to set arguments for the launch on login feature. Now we can!
=> feat: add autolaunch args

src/creator.ts, static/wix.xml
As with other properties in the wix template, it can
be useful for users of this library to override both
the reboot behavior (e.g. in cases they want to allow
reboots), as well as the install level (e.g. if they
want to exclude install level 2 features or include
install level 3 features without customers having to
use ADDLOCAL or other manual mechanisms).
This change makes both of those properties configurable,
defaulting them to their existing behavior.
It also cleans up a leftover comment (there were two sets
of descriptions for INSTALLPATH; this change removes the
older, misplaced version.
msi created after this change, without setting any custom configs:
--> We can see INSTALLLEVEL is set to 2, and REBOOT is set to "ReallySuppress"
In this attempt, I added the following two lines to …
=> Make INSTALLLEVEL and REBOOT properties configurable

__tests__/creator-spec.ts, __tests__/utils/rc-edit-spec.ts
Some tests are currently failing because they are
reading the current year and comparing it against
"2020".
This change updates the tests to expect "2021" instead.
=> Update tests for 2021

README.md, __tests__/creator-spec.ts, src/creator.ts
This adds the ability to pass command line options to light.exe
I found I needed this in order to build my app as part of a Jenkins pipeline which required the `-sval` option to be set.
I called the configuration parameter `lightSwitches` partly to fit in with the rest of the wix terminology, but I'm happy to change it to something clearer if you have any suggestions.
=> Options for light

package-lock.json, package.json, src/creator.ts, static/directory-nested-install.xml, static/wix.xml
I made multiple changes to fit my needs:
I had to bundle two MSIs together using Burn. One was an electron app and one created in VS with WIX. When bundling, I was getting the following error:
```
ALLUSERS Property is set to '2' which may change from per-user to per-machine at install time. The Bundle will assume the package is per-machine and will not work correctly if that changes. If possible, remove the Property with Id='ALLUSERS' and use Package/@InstallScope attribute instead.
```
I noticed there is no simple way to set `InstallScope` in the `wix.xml` template. `defaultInstallMode` seems to not help. I just decided to use `defaultInstallMode` to set a `{{packageScope}}` in the XML.
It may be desired to have an individual `InstallScope` variable, but some way to modify that would be …
=> Allow Config of Installscope Instead of ALLUSERS, Burn Bundled Config Flag, and Nested Directory Installation

README.md, e2e/src/utils/msi-packager.ts, harness/harness.js, src/creator.ts
Co-authored-by: Keeley Hammond <vertedinde@electronjs.org>
This change aims to bring icon path config names in line with other `electron-forge` `makers` to improve clarity for users.
note that this would be a breaking change as this is an option name, and would need to be communicated in the forge release notes.
related issue: github.com/electron-userland/electron-forge/issues/1994
related guide doc for forge: https://github.com/electron-forge/electron-forge-docs/pull/74/files
=> feat!: rename icon path fields to be consistent

README.md, __tests__/creator-spec.ts, package-lock.json, package.json, src/creator.ts, src/interfaces.ts
Small but mighty addition: This PR adds `@electron/windows-sign`. That way, over in `electron/electron`, we can document the same options across the board: Since `@electron/packager` and `electron-winstaller` already use `@electron/windows-sign`, developers just have to learn one single set of options.
=> feat: Use @electron/windows-sign
